#!/usr/bin/env node
// ═══════════════════════════════════════════════════════════════════════════
// PUBLISH SHOWS — every analyzed song gets a full show.
//
// canPerform() gates on tracks.lyrics_synced.words[] alone, and the batch
// analyzer produced word-level timings (transcript.json) + a planet analysis
// (<id>-planet-full.json) for every track. This script turns those into SQL:
//
//   • lyrics_synced  — set ONLY where the row has none (official synced
//     lyrics from real onboards are sacred; whisper timings are the fallback)
//   • lyrics (LRC)   — set ONLY where the row has none
//   • planet.analysis — set ONLY where the planet has no analysis yet
//
// Emits scripts/song-analysis/shows.sql for review + apply. Nothing touches
// the DB from here. Idempotent: the WHERE guards make re-applies no-ops.
//
//   node scripts/song-analysis/publish-shows.mjs [--only slug,slug]
// ═══════════════════════════════════════════════════════════════════════════

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const PROFILES = join(HERE, "profiles");
const only = process.argv.includes("--only")
  ? new Set(process.argv[process.argv.indexOf("--only") + 1].split(",")) : null;

// dollar-quote payloads so lyrics apostrophes can't break the SQL
const dq = (s) => { let tag = "$j$"; while (s.includes(tag)) tag = `$j${tag.length}$`; return `${tag}${s}${tag}`; };

const ids = readdirSync(PROFILES).filter((d) => existsSync(join(PROFILES, d, "profile.json")));
let sql = `-- generated by publish-shows.mjs — full shows for every analyzed song\n`;
let n = 0;

for (const id of ids) {
  if (only && !only.has(id)) continue;
  const dir = join(PROFILES, id);
  const transcript = JSON.parse(readFileSync(join(dir, "transcript.json"), "utf8"));
  const words = (transcript.segments ?? []).flatMap((s) => s.words ?? [])
    .filter((w) => typeof w.t === "number" && w.text)
    .map((w) => ({ t: Math.round(w.t * 100) / 100, w: String(w.text) }));
  if (!words.length) { console.error(`skip ${id}: no timed words`); continue; }

  const planetFull = JSON.parse(readFileSync(join(dir, `${id}-planet-full.json`), "utf8"));
  const analysis = planetFull.analysis;
  const lrc = existsSync(join(dir, "lyrics.lrc")) ? readFileSync(join(dir, "lyrics.lrc"), "utf8") : null;

  sql += `\n-- ${id}: ${words.length} words, ${analysis?.sections?.length ?? 0} sections\n`;
  sql += `UPDATE tracks SET lyrics_synced = ${dq(JSON.stringify({ words }))}::jsonb WHERE id = '${id}' AND (lyrics_synced IS NULL OR jsonb_array_length(coalesce(lyrics_synced->'words','[]'::jsonb)) = 0);\n`;
  if (lrc) sql += `UPDATE tracks SET lyrics = ${dq(lrc)} WHERE id = '${id}' AND coalesce(lyrics,'') = '';\n`;
  if (analysis) sql += `UPDATE tracks SET planet = jsonb_set(coalesce(planet,'{}'::jsonb), '{analysis}', ${dq(JSON.stringify(analysis))}::jsonb) WHERE id = '${id}' AND planet->'analysis' IS NULL;\n`;
  n++;
  console.error(`✔ ${id} (${words.length} words)`);
}

writeFileSync(join(HERE, "shows.sql"), sql);
console.error(`\n${n} tracks → ${join(HERE, "shows.sql")} — review, then apply to Supabase.`);
